apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: my-custom-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: NAME
          value: "Guowei"
        - name: MYSQL_DB_HOST
          value: mysql           
        - name: MYSQL_DB_PORT
          value: "3306"            
        - name: MYSQL_DB_NAME
          value: "friends"            
        - name: MYSQL_DB_USER
          value: "admin"             
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
  labels:
    app: custom-nginx
spec:
  selector:
    app: custom-nginx
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: LoadBalancer

